# SPDX-License-Identifier: GPL-2.0-or-later

INCLUDES := -I$(KDIR)/include
INCLUDES += -I$(src)/../../include
INCLUDES += -I$(src)/../../include/link
INCLUDES += -I$(src)/../../include/flea

ccflags-y := -D__KERNEL__ -DMODULE $(INCLUDES) $(INC)
ccflags-y += -Wall -Wstrict-prototypes -Wno-trigraphs -Werror -O2

obj-m := crystalhd.o
crystalhd-objs := crystalhd_lnx.o \
	crystalhd_misc.o \
	crystalhd_cmds.o \
	crystalhd_hw.o \
	crystalhd_linkfuncs.o \
	crystalhd_fleafuncs.o \
	crystalhd_flea_ddr.o
